### PR TITLE
Fix validation and translation errors on broadcast creation.

### LINKED ISSUE #862: Broadcast create should not require a valid ULR
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**
If I try create a broadcast with a given title, description and a medium (TV) on http://localhost:4200/find-broadcasts?q=titleofthebroadcastiwanttocreatexxxslkdjfsalkfdj and hit submit, I see an error with a missing translation.

* **What is the expected behavior?**
First of all, creating a broadcast without a URL should be fine. In any case, there should not be a missing translation from the backend.

* **What is the motivation / use case for changing the behavior?**
Broadcast URLS are nice, but some don't even have a website.

* **If the current behavior is a bug, please tell us (otherwise delete):**
  * Steps to reproduce
1. Search for a broadcast title that does not exist
2. Fill out the form
3. Leave out URL
4. Hit submit

download

### PR DESCRIPTION
**Pull request by ciremoussadia**
An empty string should be nil before validation on the broadcast url and
image url. This is done because the presence of an empty string should
be valid and it is nullified in order to prevent broken links with empty
url's.

Fixes #862

### CODE REVIEW

File: backend/app/models/broadcast.rb [hunk 1]
```diff
@@ -14,6 +14,8 @@ class Broadcast < ApplicationRecord
 
   has_many :impressions, dependent: :destroy
 
+  before_validation :normalize_url, on: %i[create update]
```
Comment (roschaefer) [inline backend/app/models/broadcast.rb]: Does it hurt to normalize it on all requests? :thinking:

**Comment by roschaefer** [comment]
No no! Miscommunication, sorry. I mean the symbol of the translation key. We have redundancy, because we're using the same text for two attributes. Can we DRY this?

**Comment by ciremoussadia** [comment]
@roschaefer yeah it's more clear now. Ok I can give it a try.

File: backend/app/models/broadcast.rb (hunk 1 above)
Comment (roschaefer) [reply backend/app/models/broadcast.rb]: I suggest to remove `, on: %i[create update]`, I don't think it will hurt to have it on `:delete`, too. That's what I mean by "all requests".

Usually, I think every piece of code is there for a reason and I just asked myself: Why does he explicitly restrict it to `:create` and `:update`? Probably performance?

Comment (ciremoussadia) [reply backend/app/models/broadcast.rb]: We care to normalize only when we create or update because we don't want to have db column with blank value. I don't think we care to normalize when we delete.

Comment (roschaefer) [reply backend/app/models/broadcast.rb]: Yeah! That's what I thought. We care not to care in certain cases to normalize. :laughing: 

It's good! It's alright. Keep it there :slightly_smiling_face: :+1:

**Comment by roschaefer** [comment]
Thank you so much! :heart:

**Comment by ciremoussadia** [comment]
@roschaefer @NickSchimek thank you. I was a pleasure to pair with @NickSchimek .

**Comment by NickSchimek** [comment]
The pleasure was all mine @ciremoussadia ! Let's do it again sometime.
