### PR TITLE
353 pagination bug

### LINKED ISSUE #353: Find-broadcast: Pagination bug
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**
When I visit https://rundfunk-mitbestimmen.de/find-broadcasts?medium=0&q=&station=36 it says there are 12 broadcasts for TV station "BR Fernsehen". When I click on "Next", some broadcasts appear twice and at least "Startrampe" never appears.

* **What is the expected behavior?**
All broadcasts should appear and they should appear only once.

* **What is the motivation / use case for changing the behavior?**
I don't want to miss a broadcast!

* **If the current behavior is a bug, please tell us (otherwise delete):**
  * Steps to reproduce
    1. Visit https://rundfunk-mitbestimmen.de/find-broadcasts?medium=0&q=&station=36
    2. Click on "Next" and pay attention!
    3. See that e.g. broadcast "Wirtshausmusikanten" shows up twice
    4. It says "12 broadcasts" next to the search bar, but there are 3 pages with 5 broadcasts :thinking: 

  * The version of your browser, local postgresql installation and operating system
    Chromium Version 61.0.3163.100, Postgresql 9.6.5., Archlinux
  * A screenshot
selection_076
selection_079
selection_080

  * Stacktraces, related issues, suggestions how to fix

* **What could be a possible solution? (not obligatory)**
I'm pretty sure, we forgot a default order in the broadcasts controller. In that case, the database randomly puts records in the result set.

### PR DESCRIPTION
**Pull request by roschaefer**
close #353

This was probably the hardest to reproduce bug in my life so far. It only appears when:
* You search for a station
* and order randomly
* and use pagination
* and there is a broadcast in the result set with many stations (called troublemaker)
* and the troublemaker has some impressions
* and there are some more broadcasts in the result set

What happens is that the LEFT OUTER JOIN of impressions joins in the troublemaker more than just once. The pagination gets confused because it adds some duplicate `broadcast_id` to the IN clause. Every duplicate id in the IN-clause will reduce the final result set. That's the reason why we get less than 6 results.

### CODE REVIEW

File: backend/spec/models/broadcast_spec.rb [hunk 1]
```diff
@@ -151,6 +151,36 @@
...
+          end
+
+          describe 'size of entire result set' do
+            subject { relation.count }
+            it { is_expected.to eq(10) }
+          end
+
+          describe 'size of paginated result set' do
+            subject { relation.page(1).per(6).count }
+            it { is_expected.to eq(6) }
```
Comment (roschaefer) [inline backend/spec/models/broadcast_spec.rb]: this is the exposing test (fails when you LEFT OUTER JOIN impressions)

File: backend/app/models/broadcast.rb [hunk 2]
```diff
@@ -48,7 +48,7 @@ class Broadcast < ApplicationRecord
   end
 
   def self.search(query: nil, filter_params: nil, sort: nil, seed: nil, user: nil)
-    results = Broadcast.all.includes(:impressions)
```
Comment (roschaefer) [inline backend/app/models/broadcast.rb]: We don't need to LEFT OUTER JOIN `:impressions` and we shouldn't. It messes up pagination.
